[package]
name = "xvm"
version = "0.1.0"
edition = "2021"
authors = ["andreweathan <mariluu69420@gmail.com>"]

[dependencies]
crossterm = "0.25.0"
pancurses = "0.17.0"
tui = "0.19.0"

# [dependencies]
# sdl2 = "0.35.2"
